### ISSUE TITLE
Repository not found while syncing the repo.

### ISSUE THREAD

**Issue by bluejeans117** [Evolution-X/platform_manifest#1]
Everything is synced, until we come to the repo located at
[https://github.com/pe-wip/hardware_ril-caf](https://github.com/pe-wip/hardware_ril-caf/)
There is no such repo, and so the syncing doesn't complete. Please guide me on how to proceed with this. This is while syncing for branch "ten"

**Comment by AnierinBliss** [comment]
@bluejeans117 Ouch

**Comment by Stallix** [comment]
Ten branch is **NOT READY AT ALL**.

**Comment by bluejeans117** [comment]
@Stallix I see. How about the ten branch at PE git tho?

**Comment by Stallix** [comment]
> @Stallix I see. How about the ten branch at PE git tho?

Not my project. Ask them.
